// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivitklsxrkcxhckuhuix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2aXRrbHN4cmtjeGhja3VodWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNTgwMTUsImV4cCI6MjA3NTgzNDAxNX0.043CgaN1scdRm3yYIgCxubM3wWWR_wNvlJhhnxzECgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});